import { useQuery } from "@tanstack/react-query";
import ky from "ky";

import { MocBoard } from "../types";

const API_URL = import.meta.env.VITE_API_URL;

const mocBoards = [
  {
    id: 28,
    name: "American Board of Otolaryngology – Head and Neck Surgery (ABOHNS)",
    types: [
      "Patient Safety",
      "Improvement in Medical Practice (Part IV)",
      "Lifelong Learning (CME)",
      "Self-Assessment Module (Part II)",
    ],
    specialties: [
      "Allergy",
      "Facial Plastic & Reconstructive Surgery",
      "Head & Neck",
      "Laryngology",
      "Otology",
      "Neurotology",
      "Pediatric Otolaryngology",
      "Rhinology",
      "Sleep Medicine",
      "General Otolaryngology",
    ],
  },
  {
    id: 29,
    name: "American Board of Orthopaedic Surgery (ABOS)",
    types: ["Accredited CME", "Self-Assessment Examination (SAE)"],
    specialties: [
      "Adult Reconstruction",
      "Foot and Ankle",
      "General Orthopaedics",
      "Musculoskeletal Oncology",
      "Orthopaedic Sports Medicine",
      "Orthopaedic Trauma",
      "Pediatric Orthopaedic Surgery",
      "Shoulder and Elbow",
      "Surgery of the Hand",
      "Surgery of the Spine",
    ],
  },
  {
    id: 30,
    name: "American Board of Pediatrics (ABP)",
    types: ["Lifelong Learning and Self-Assessment (Part II)"],
    specialties: [
      "Adolescent Medicine",
      "Child Abuse Pediatrics",
      "Developmental-Behavioral Pediatrics",
      "General Pediatrics",
      "Hospice & Palliative Medicine",
      "Hospital Medicine",
      "Medical Toxicology",
      "Neonatal-Perinatal Medicine",
      "Neurodevelopmental Disabilities",
      "Pediatric Cardiology",
      "Pediatric Critical Care Medicine",
      "Pediatric Emergency Medicine",
      "Pediatric Endocrinology",
      "Pediatric Gastroenterology",
      "Pediatric Hematology-Oncology",
      "Pediatric Infectious Diseases",
      "Pediatric Nephrology",
      "Pediatric Neurology",
      "Pediatric Pulmonology",
      "Pediatric Rheumatology",
      "Pediatric Transplant Hepatology",
      "Sleep Medicine",
      "Sports Medicine",
      "Professionalism/Patient Safety/Other Skills",
    ],
  },
  {
    id: 34,
    name: "American Board of Internal Medicine (ABIM)",
    types: [
      "Medical Knowledge (Part II)",
      "Patient Safety",
      "Practice Assessment (Part IV)",
    ],
    specialties: [
      "Adolescent Medicine",
      "Adult Congenital Heart Disease",
      "Advanced Heart Failure and Transplant Cardiology",
      "Cardiovascular Disease",
      "Clinical Cardiac Electrophysiology",
      "Critical Care Medicine",
      "Endocrinology, Diabetes, and Metabolism",
      "Gastroenterology",
      "Geriatric Medicine",
      "Hematology",
      "Hospice and Palliative Medicine",
      "Hospital Medicine",
      "Infectious Disease",
      "Internal Medicine",
      "Interventional Cardiology",
      "Medical Oncology",
      "Nephrology",
      "Neurocritical Care",
      "Pulmonary Disease",
      "Rheumatology",
      "Sleep Medicine",
      "Sports Medicine",
      "Transplant Hepatology",
    ],
  },
  {
    id: 35,
    name: "American Board of Pathology (ABPath)",
    types: [
      "Improvement in Medical Practice (Part IV)",
      "Self-Assessment (Part II)",
      "Lifelong Learning (CME)",
    ],
    specialties: [
      "All Practice Areas (e.g. ethics)",
      "Surgical Pathology",
      "Clinical Pathology",
      "Blood Bank Transfusion Medicine",
      "Breast",
      "Cardiovascular",
      "Chemical Pathology",
      "Clinical Informatics",
      "Cytopathology",
      "Dermatopathology",
      "Endocrine",
      "Female Reproductive",
      "Forensic Pathology",
      "GI (Incl. Liver, Pancreas, Bilary)",
      "Head & Neck/Oral",
      "Hematology (Blood, BM)",
      "Hematopathology (LN, Spleen)",
      "Hemostasis & Thrombosis/Coagulation",
      "Infectious Diseases/Medical Microbiology",
      "Lab Management",
      "Male Genital",
      "Medical Director",
      "Molecular Genetic Pathology",
      "Neuropathology (incl. Neuromuscular)",
      "Patient Safety",
      "Pediatric Pathology",
      "Placenta",
      "Pulmonary, Mediastinum",
      "Renal/Medical Renal",
      "Soft Tissue & Bone",
      "Transplant Pathology",
      "Urinary Tract",
    ],
  },
  {
    id: 36,
    name: "American Board of Surgery (ABS)",
    types: ["Self-Assessment (Part II)", "Accredited CME"],
    specialties: [
      "Complex General Surgical Oncology",
      "Hand Surgery",
      "Hospice & Palliative Medicine",
      "Neurocritical Care",
      "Pediatric Surgery",
      "Surgical Critical Care",
      "Vascular Surgery",
      "General Surgery",
      "Bariatric Surgery",
    ],
  },
  {
    id: 38,
    name: "American Board of Anesthesiology (ABA)",
    types: ["Lifelong Learning (CME)", "Patient Safety"],
    specialties: [
      "Ambulatory/Outpatient",
      "Cardiac Anesthesia",
      "Critical Care Medicine",
      "General Operative Anesthesia",
      "Hospice and Palliative Medicine",
      "Neuro Anesthesia",
      "Neurocritical Care",
      "Obstetric Anesthesia",
      "Pain Medicine",
      "Pediatric Anesthesia",
      "Regional Anesthesia/Acute Pain",
      "Sleep Medicine",
      "Thoracic Anesthesia",
      "Trauma",
    ],
  },
];

//TODO: Replace with API
async function getMocBoards(): Promise<MocBoard[]> {
  return mocBoards;
}

export function useMocBoards() {
  return useQuery({
    queryKey: ["mocBoards"],
    queryFn: getMocBoards,
  });
}
